### PR TITLE
feat: updated issue template with figma links

### LINKED ISSUE #19: Issue Template Updates for Figma link
### Current Behavior
The project's current issue templates are missing an open invitation link where new contributors can join the community's Figma team and view user interface designs and other UX projects.

### Desired Situation
Each template that has a reference to Figma in its resources section should an invite link added.

### Implementation 
```
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
```

**Acceptance Tests**
All references to Figma include the "open invite" link.

---
**Resources**

**Alternatives / Additional Context**

### PR DESCRIPTION
**Pull request by abhijeetgauravm**
**Description**

This PR fixes #19  

**Notes to reviewers**

#### Checklist

- [x] [Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin).
- [ ] PR title includes `[<name of area>]:<description>`

### CODE REVIEW

**Review by thisiskaransgit — COMMENTED** [review]
@abhijeetgauravm , include the *Contributors Resources*  section at the footer in the templates which do not have them. Exclude the documentation.md

:books: See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
:art: Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io/) and [Community Slack](https://slack.layer5.io/).

**Comment by abhijeetgauravm** [comment]
@thisiskaransgit can u review ?

**Review by thisiskaransgit — COMMENTED** [review]
@abhijeetgauravm, keep the cta for questions as a point below the wireframes points

**Comment by abhijeetgauravm** [comment]
> @abhijeetgauravm, keep the cta for questions as a point below the wireframes points

@thisiskaransgit means should i remove the icons(emojis) just before the questions ?

**Pull request merged**
