### PR TITLE
[README]: Added Community Forum

### LINKED ISSUE #11: [README] Need to add `Community Forum`
**Description**

<a href="https://github.com/layer5io/containers-101-workshop/blob/master/README.md">README.md</a> is the first file one should read when starting a new project. Our community launched `Discussion forum` for help seekers; needs to publish it officially on README.md for convenience.

### Screenshots

**Current behaviour:**
image

**Desired behaviour:**
image

**Note:**
Need to add only last line for `Community Forum`

**Environment:**
 - OS: any [e.g. Ubuntu]
 - Browser: any [e.g. Chrome, Safari]
 - Version: any [e.g. 22]
 - Device: any [e.g. laptop, iPhone 8]

---
**Reference:**
- Take reference to this <a href="https://github.com/layer5io/layer5/pull/1949">pull request</a>

### PR DESCRIPTION
**Pull request by debo19**
Signed-off-by: Debopriya Bhattacharjee <debopriyabh1908@gmail.com>

**Description**

This PR fixes #11  

**Notes to reviewers**

#### Checklist

- [x] [Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin).
- [x] PR title includes `[<name of area>]:<description>`

### CODE REVIEW

**Review by includestdlibrary — APPROVED** [review]
LGTM @sayantan1413 will you review?

**Comment by debo19** [comment]
Thanks @includestdlibrary I've changed it.

**Comment by includestdlibrary** [comment]
> Thanks @includestdlibrary I've changed it.

Great!! And thank you for contributing! :)

**Comment by sayantan1413** [comment]
@debo19 Please mention the `This PR fixes #<issue number>` and please give a check mark to the checklist so that you can confirm the checks. Otherwise Looking good to me. Great Work @debo19 . :smiley:

**Comment by debo19** [comment]
Thanks @sayantan1413.  Done :)

**Review by leecalcote — APPROVED** [review]
Thank you, @debo19 and @includestdlibrary 👍

**Pull request merged**
