### PR TITLE
[containers-101-workshop]:Update the community drive access message and associated link

### LINKED ISSUE #9: [README] Update README Community Section
**Description**
The Community section in the README says "Access the Community Drive". There is a new procedure of having this automated based on the individual filling in a [community member form](https://layer5.io/newcomer)

**Expected Behavior**
Update "Access Community Drive" to "To Access Community Drive, fill Community Member Form"

**Screenshots**
img
--

**Resources**
Refer to the [Contributing guide](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#contributing)

**Environment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

### PR DESCRIPTION
**Pull request by josephmidura**
Signed-off-by: Joseph Midura <josephmidura632@gmail.com>

**Description**

This PR fixes #9

**Notes to reviewers**

Updated the community drive access message and link to the community member form

#### Checklist

- [ x] [Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin).
- [ x] PR title includes `[<name of area>]:<description>`

### CODE REVIEW

**Review by Anita-ihuman — COMMENTED** [review]
For Consistency across all repositories, please use this text provide
"To Access Community Drive, fill Community Member Form"

**Comment by josephmidura** [comment]
I have two questions:

1. Should any of the words be bold like "join" or "watch" in the two lines above it?
2. Should "Community Member Form" or just "Form" be the link?

Thanks

**Comment by Anita-ihuman** [comment]
> I have two questions:
> 
> 1. Should any of the words be bold like "join" or "watch" in the two lines above it?
> 2. Should "Community Member Form" or just "Form" be the link?
> 
> Thanks
1. This text should just be "To Access Community Drive, fill Community Member Form".
2. Yes, "Community Member Form" or should be a wrapped in a link tag directing to this link. http://layer5.io/newcomer

**Review by Anita-ihuman — COMMENTED** [review]
Great work. You are good to go.

**Review by Anita-ihuman — APPROVED** [review]

**Comment by leecalcote** [comment]
Thank you, @josephmidura and @Anita-ihuman 👍

**Pull request merged**
