### PR TITLE
[Docs] - Added Release Drafter

### LINKED ISSUE #7: Add Release Drafter for the repository
**Current Situation**

Each of the layer5 repositories needs releaseDrafter automation as had been done in the meshery project which takes care of drafting release notes.

**Desired Situation**

Add ReleaseDrafter configuration yaml file & GitHub Action.

**Additional context**

[ReleaseDrafter Configuration File](https://github.com/layer5io/meshery/blob/master/.github/release-drafter.yml)
[ReleaseDrafter GitHub Action](https://github.com/layer5io/meshery/blob/master/.github/workflows/release-drafter.yml)

**Contributor Resources**

See[ layer5 contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by adithyaakrishna**
Signed-off-by: Adithya Krishna <aadithya794@gmail.com>

**Description**

This PR fixes #7  and also Fixes the PR Template

**Notes to reviewers**

#### Checklist

- [X] [Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin).
- [X] PR title includes `[<name of area>]:<description>`

### CODE REVIEW

**Comment by adithyaakrishna** [comment]
@Anita-ihuman Could you review this Please? :)

**Comment by adithyaakrishna** [comment]
@Nikhil-Ladha Could you please review this? 👀

**Review by leecalcote — CHANGES_REQUESTED** [review]
Lgtm

**Comment by adithyaakrishna** [comment]
Thank You @leecalcote 
Now this repository is free of issues 🎉

**Pull request merged**
